# Generated by Django 3.1.5 on 2021-01-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
